[package]
name = "tauri-runtime-verso"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "tauri-runtime-verso-build",
    # Examples
    "examples/helloworld",
    "examples/api/src-tauri",
]

[workspace.dependencies]
verso = { git = "https://github.com/versotile-org/verso", rev = "bbabe5f1874b6c9b8f58223499051d0fb13a1574" }
versoview_build = { git = "https://github.com/versotile-org/verso", rev = "bbabe5f1874b6c9b8f58223499051d0fb13a1574" }

[features]
# Required if you use tauri's macos-private-api feature
macos-private-api = ["tauri-runtime/macos-private-api"]

[dependencies]
verso = { workspace = true }
tauri = { version = "=2.4.1", default-features = false }
tauri-runtime = "=2.5.1"
tauri-utils = "=2.3.1"
raw-window-handle = "0.6"
url = "2"
http = "1"
percent-encoding = "2"
log = "0.4"

[target."cfg(windows)".dependencies]
windows = "0.60"

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
gtk = { version = "0.18", features = ["v3_24"] }

[patch."https://github.com/versotile-org/verso"]
# verso = { path = "../verso/verso" }
# versoview_build = { path = "../verso/versoview_build" }

[lints.clippy]
needless_doctest_main = "allow"
