[package]
name = "tauri-runtime-verso"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["examples/helloworld", "examples/api/src-tauri"]

[features]
# Required if you use tauri's macos-private-api feature
macos-private-api = ["tauri-runtime/macos-private-api"]

[dependencies]
verso = { git = "https://github.com/versotile-org/verso", rev = "58bd22b5ead5b1531c4142a4c22e34b296cdee9c" }
tauri = { version = "=2.4.0", default-features = false }
tauri-runtime = "=2.5.0"
tauri-utils = "=2.3.0"
raw-window-handle = "0.6"
url = "2"
http = "1"
log = "0.4"
tempfile = "3"

[target."cfg(windows)".dependencies]
windows = "0.60"

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
gtk = { version = "0.18", features = ["v3_24"] }

[patch."https://github.com/versotile-org/verso"]
# verso = { path = "../verso/verso" }

[lints.clippy]
needless_doctest_main = "allow"
