[package]
name = "tauri-runtime-verso"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["examples/helloworld"]

[features]
# Required if you use tauri's macos-private-api feature
macos-private-api = ["tauri-runtime/macos-private-api"]

[dependencies]
verso = { git = "https://github.com/versotile-org/verso", rev = "cf4148e" }
tauri = { version = "=2.3.1", default-features = false }
tauri-runtime = "=2.4.0"
tauri-utils = "=2.2.0"
raw-window-handle = "0.6"
url = "2"
http = "1"
log = "0.4"
tempfile = "3"

[target."cfg(windows)".dependencies]
windows = "0.60"

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
gtk = { version = "0.18", features = ["v3_24"] }

[patch."https://github.com/versotile-org/verso"]
# verso = { path = "../verso/verso" }
