name: Test Hello World Example

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --package helloworld
