name: Test Hello World Example

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-hello-world-example:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: matrix.platform.target == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libxdo-dev libayatana-appindicator3-dev

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --package helloworld
